### PR TITLE
WIP: Release 0.1.1

### LINKED ISSUE #4: Release 0.1.1

### PR DESCRIPTION
**Pull request by yurrriq**
This will close #4.

### CODE REVIEW

**Comment by fenollp** [comment]
This works great. There's only a few compilation warnings:
```
_build/default/lib/elli_websocket/src/elli_ws_request_adapter.erl:239: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

_build/default/lib/elli_websocket/src/elli_ws_protocol.erl:60: Warning: type mask_key() is unused
_build/default/lib/elli_websocket/src/elli_ws_protocol.erl:63: Warning: type rsv() is unused
```

Without this patch I couldn't use this project with elli-2.1.2 & otp 21.0.9.

When do you think this can be on Hex along with elli v3 support?
Thanks

**Comment by yurrriq** [comment]
I'd gladly review a PR to squash those warnings. Otherwise I'll try to get to it, and publishing to Hex, sometime this week.

**Comment by fenollp** [comment]
@yurrriq beat you to it ;)

**Comment by fenollp** [comment]
Yes this looks ready on my part

**Pull request closed without merging**
